version: '2'
services:
 traffic-light-mysql:
   container_name: traffic-light-mysql
   environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
     - MYSQL_DATABASE=trafficlight
   image: mysql:5.7
   ports:
     - 3308:3306
   volumes:
     - ./schemas/database.sql:/docker-entrypoint-initdb.d/database.sql
